version: "3"
services:
  redis-server:
    image: "redis"
    ports:
      - "6379:6379"
  node-app:
    container_name: reto-culqi
    build: .
    ports:
      - "4001:3000"
    environment:
      - JWT_SECRET="CULQI_CHALLENGE"
      - AUTORIZATION=pk_test_LsRBKejzCOEEWOsw
      - SECOND_EXPIRATION=60
      - PORT=3000
      - HOST=redis-server
      - PORTREDIS=6379
