apiVersion: v1
kind: Service
metadata:
  name: reto-culqi-service-np
  labels:
    name: reto-culqi-deploy
    app: reto-culqi-app
spec:
  type: NodePort
  selector:
    app: reto-culqi-app
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 30072
